dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  edge: true
  api_key:
    - secure: "OWWSiYjl9VM8iP6z7xsRR+jAZmRsUXevNPc3560ngJtmIa0xgZCwcCjShmxLEquY87B60NN9q9GjRZJ3WjKttqLBdG2mit+Xsez0q3OgJVfWH+iw/mVSUT4bueVptmZw9/bgeZhl8cIrber8xPt9ISgCMm+9yi+7bqaJMgpvHSdL6HPqu5tpRxi1lePzIEpQmofWL6J2pC4YgblupZBa2joEwByOP/rAD7nfn1+lfBVRYij/+JkAjkESdi3nGdeKtjvmQp3jxeTnyyvJG3QTdqafgbWpcXc6fqHvCklo6aZCvdYZeAo4RJbbQFJ2JQsYPR4wtm7hvrr2dHlWFNoWp5m1zgfUbLeNYTHa0MQC/4/2/kAYfrMp2eWdtyx5HiyjCLMylX+/uNhj0x16RcoRRcsX6YSYWez0aLGmsWoDk37HFKXQz6CY/1OnQmmvbOqyLcBbaq8Lwn1JD4YZhg41KlW+yvNO2dpdIrN/beaa0d6v+zgpxlbmcNqE7VZPW11oCOWcvhlEewt4ZMH7cJjXiPnszmOXe9aHXBhEqIHk6aKcCdeyqCqyN0cNvnsIAmHcd8+uMWAMnb2z3tjFAEUDsG8TRlxlo1aVj/3ayGgswJ5fxPe7rd6U/1PnhsIa84DwL/qcit+8eld3VJwO1GW7yJxEIbvZ98mSytSNwDTfEe8="
#Teste
