dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  app: zabbix2
  on:
    branch: master
  edge: true
  api_key:
    secure: SSIk0BOpEPW7R3681Tm46G1eLoOuD513BtgBsUZYb2sxM7MxD5/X7hGRuIyT5w9LER2NXcxZNKbGYuPgqa3w3edq2bGEpdVPPscCOoJwAd5Yz5Nz9X7+koJ8vD0vEFXtrzn9pHgmrcb+NaYQh64/BMHNfRY0G+dy3KUbqL3ep/I3wYPgcnEdcHzA58u5Gxg6wIXLf6YOMgzLZRY8fGVZNNYsYaU+R0HNAeRoYD3ZbO2+P/3wcnwuc63vPNqpfaYmwUylS6mwFFo9UXs0r+140JjVBepNR/EMZpQhU33RvjWbpkkm5h7R6DebtQoRMWciGU/yms8K3huALewhLrXGkO0CphoAeRjw64bgM8wAIy1KiuQbvyBaFUcH0s942/UeY6tDjmGDAJtzEdGj9VeFd8YJCMhLHvmONRutl0KxAez5tU9Rqq4fTphNg6dn5lC3uWoylQsbMRlGT/GHdpWILKSgOQ4bGUxKEPc43Ihp7BPoxcJO5Zr/qcWh5mDTHaeK5jrhNMwyYGBAeaCjiKBBYiL6fwgM+6JsHN/CvokWuyRsz8e7UWKu1ytU1eKC8HVchbk9m+2f+7hc2cQfRYc0vB2afJX60wzVgYRwiESDUORCCjQKoxYw1mBH8WPlY915Z3t6XQxLIva3i5ISTIzUtUjLnglOkmn71V4DjMb8cyA=
