dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
- travis encrypt $HEROKU_API_KEY --add deploy.api_key
deploy:
  provider: heroku
  edge: true
  api_key:
    - secure: $HEROKU_API_KEY
#Teste
