dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  edge: true
  api_key:
    - secure: "E+Lj7QAQKcc8qEhP32RZChaFLZBmG3AwNfP2YUHRsG0JiZ70FtOVyjkaagpTPrNC7DMpMAjFcTM7SbtHVbMjK7fjoi6BtHHgxbDsZTKVIu8upBudqHz0jFCfzw8zQD7rV4aVNjgG7SH5BNnISeC8Bs4a8gvq7xiaWq7CyliQm3616IgIsx52b7VDaiPp1g4LyGLpsVma0iogZSclZFuKyZgtf7WHdJVgPv7TG8mvIRT+9kGiJ32iW3eQ1noNsNGNo3gv1DZDDrd+Uc7SJCwnEUUz+rZCzpg6bZBAYXL1IR7koAK2QMWf/Psx7GVvGCnHxt9SXFvtnU96Bsxb24fsBToUhNQOW+22SeNToAZxOHkgG7rIbWDm/6hsN5vnu9PErPmDTkv4K+PBlq7S/oFg+PMalGHZa2ve5KKmioTseVwPKW4t2y0K3r1sPSrq5eZr+3TKufyY+c3qPIPi4uGZzdFRtOFRVommSZjS55ZrC2+Nn/BLRqeQQL7AD1s261qhp07DCAMK5j9AT3bnBZEQdPeTmHUtnXcgrwgJky0fJk6MlvpGZpj/gwWyJsXIO60Am+Z4XvcvPAc6EyALkkNd1IOjJkNY2PC3CR8i4yO0Vt1ee9UNKFuHMcvT2WiPVIxWJ17FMtdKYtX0OnVHzA5sxoleTedxXmAWc5l3xjcKbcQ="
    - app: "zabbix2"
