dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  edge: true
  api_key:
    - secure: "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAm8Yx2BnS52udF0DdIhTU Xm7TlwfLa0cxdjBfsh0Skips0NhZG6edQefNh3J4YJpeWaP5k3XCmUnimbkd4BGv bvBvV81STowDhV/dhSsFrX5HIwuDmlsVbhdVbzmEjHoMRLGs5q9ylzy2IO40Aszj duqu10qKnJO1X5AxdC/4+TZyP+ynVbTcY75imdRtZdgLxQVHS1fW1HWNv2DUzq2f TVmDMjuA7oeBUq6kZeYOji5Fxq14xons4ny+qAMJdtO+JWuPPhO0tBJr1jbrcNxi nk1JKCj4vluGp8d+HoBrNOJHZo6chRuLWpHGMfo094PVL3wjEn0BdDpGxmwm/XQd R8DIkwgKu+KGdSSjXh39gwbhH0DvLu7TdqXU9/NYCna5q/wBOt6MtHyWYCgLwH5Q sNs0/2PvjC+gBl9mZtviBGwD0FJarmscrzXw0zdk4E/k21MPTiC9KXjbZZlPgbXb KTZdOYMQSsqnBIL6ehy6LZV/dx6ARKVPcOtnBZDhWu9gWKg1bd6zqdilA85+sEP4 4Zjew9YPD9p0UXpyz/6fT6Gy/1chRwMr+YFTSjgY9LGGn66yCOiQD2SVnACV/z99 wKSkCc3LjoxksZegUZ5o1zTSzQJAfFYCtps1TRHKUWxuA4JGinrOQ2gw8LGiElOa 7RbwrlKfsN4tGdQQ5fsoWMkCAwEAAQ=="
    - app: zabbix2
