dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  app: zabbix2
  on:
    branch: master
  edge: true
  api_key:
    secure: MSJRNcOGGdboW4OAP15t2XjJJu9T9AlQSVcQ924colpeqWcAxiX9k4vqBgkskY3m07xd7wg7zZolxumGLxsIB77pjtGXNS1Qot1033Y4pYgmFCRxy5pbOvNrO
