dist: trusty
language: java
jdk:
- oraclejdk8
install:
- gem install bundler
- gem install travis
- gem install dpl
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  app: zabbix2
  on:
    branch: master
  edge: true
  api_key:
    secure: vn/69c6C4LBQk2U4hASKvQhbZhv84WjMWpovLWQ5sOaDCd3SS8VMRqhfFPHn9XLAiVnd9OWf4Bd40gAniyrIwDAfvRZSgvoLYEPCJqbqWRyLG8Kyw9ohMLT8KcD1bQe5Q75vd0ftjhzqF5zrrg++GDRyRJL3IimoIMO6tCd55djcSmCWywlRZKJcL/eb0e1rgMPgwM2HMZBsqXVkXuziS6Ar6eG1y6lEwI/pOq2JfUVVanuyjoZ6Qt561xSSlXlPBwWl+Qt2R59JyL6oCwxiPI14L/kaQNr5Zvse/eVEz2vBoEcOA8OT9CUro/MSWDOrHo6K61ZblTbcsUi0Q8ojm0vP2/g5LtT/YB4+eG3ncfVIhoji+qvjqjW7zceetpaD1/7SeiRpk/huDTp/jZ1ohmrAUzh57gHXO5XsCAmQ6dsP93IPWA7Gs3wZwF/02W+5rN9d3vTbT4CLwr5atlqeTDKw/8plQBUper1yMdexNJGhJCOJIL1xEq5amhg3m6fD1vul6dLjL1HJZFl0q5Aw6RT/pJo+OYr72lwQ+nPi/D9fpMyAFDq4n1O856mRCbeMYOBP9tIjUlPXxLtl4T6lqju9qYsaaoELnC1aEw3S6it3Ljb0Sd/Jd2gJlBkjfUPInDbcWEpcLgb8UJInQ9b+Jskflw2zGt4ZHIv1I/jQWxM=
